services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT_EXPORT_NEST}:${PORT}"
    volumes:
      - .:/usr/src/app
      - ./node_modules:/usr/src/app/node_modules
    env_file:
      - .env
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    ports:
      - "${PORT_EXPORT_MYSQL}:3306"
    environment:
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
